# layerrule = blur, swaync-control-center
# layerrule = ignorezero, swaync-control-center
layerrule = dimaround, swaync-control-center
# layerrule = blurpopups, swaync-control-center
layerrule = xray true, swaync-control-center

layerrule = ignorealpha 0.5, swaync-control-center
layerrule = ignorealpha 0.5, swaync-notification-window

layerrule = unset, rofi
layerrule = ignorezero, rofi
layerrule = dimaround, rofi
layerrule = xray true, rofi 

blurls = waybar
blurls = rofi
