
# external monitors
monitor=DP-1, preferred, auto-right, 1
monitor=DP-2, preferred, auto-right, 1
monitor=HDMI-A-1, preferred, auto-right, 1

monitor=desc:GIGA-BYTE TECHNOLOGY CO. LTD. G34WQC 20482B007567, 3440x1440@100, auto-left, 1
monitor=desc:Philips Consumer Electronics Company PHL24E1N5300 UK02340060703, 1920x1080, auto-right, 1
monitor=desc:Philips Consumer Electronics Company PHL24E1N5300 UK02340060723, 1920x1080, auto-right, 1
monitor=desc:Philips Consumer Electronics Company PHL 233V5 AU41440004713, 1920x1080, auto-right, 1

# built in monitor
monitor=eDP-1, 1920x1080, auto, 1.25

# monitor disposition
# BUILT IN
workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 6, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1
workspace = 10, monitor:eDP-1
workspace = 11, monitor:eDP-1
workspace = 12, monitor:eDP-1
workspace = 13, monitor:eDP-1
workspace = 14, monitor:eDP-1
workspace = 15, monitor:eDP-1
workspace = 16, monitor:eDP-1
workspace = 17, monitor:eDP-1
workspace = 18, monitor:eDP-1
workspace = 19, monitor:eDP-1
workspace = 20, monitor:eDP-1

# MAIN
workspace = 21, monitor:DP-1
workspace = 22, monitor:DP-1
workspace = 23, monitor:DP-1
workspace = 24, monitor:DP-1
workspace = 25, monitor:DP-1
workspace = 26, monitor:DP-1
workspace = 27, monitor:DP-1
workspace = 28, monitor:DP-1
workspace = 29, monitor:DP-1
workspace = 30, monitor:DP-1

# SECONDARY FALLBACK
workspace = 31, monitor:DP-1
workspace = 32, monitor:DP-1
workspace = 33, monitor:DP-1
workspace = 34, monitor:DP-1
workspace = 35, monitor:DP-1
workspace = 36, monitor:DP-1
workspace = 37, monitor:DP-1
workspace = 38, monitor:DP-1
workspace = 39, monitor:DP-1
workspace = 40, monitor:DP-1

# SECONDARY
workspace = 31, monitor:DP-2, latest
workspace = 32, monitor:DP-2, latest
workspace = 33, monitor:DP-2, latest
workspace = 34, monitor:DP-2, latest
workspace = 35, monitor:DP-2, latest
workspace = 36, monitor:DP-2, latest
workspace = 37, monitor:DP-2, latest
workspace = 38, monitor:DP-2, latest
workspace = 39, monitor:DP-2, latest
workspace = 40, monitor:DP-2, latest
