$power_menu = ~/.local/bin/hypr/rofi/powermenu.sh
$theme_switch = ~/.local/bin/hypr/rofi/change_theme.sh
$clipboard_hist = cliphist list | rofi -dmenu -lines 10 -p "cliphist" -display-columns 2 | cliphist decode | wl-copy
