# tiled

# "Smart gaps" / "No gaps when only"
# https://wiki.hyprland.org/Configuring/Workspace-Rules/

# No gaps on single window
workspace = w[tv1], gapsout:0, gapsin:0
windowrule = bordersize 0, floating:0, onworkspace:w[tv1]
windowrule = rounding 0, floating:0, onworkspace:w[tv1]

# fullscreen
workspace = f[1], gapsout:0, gapsin:0
windowrulev2 = bordersize 0, floating:0, onworkspace:f[1]
windowrulev2 = rounding 0, floating:0, onworkspace:f[1]

# pseudo restore
windowrulev2 = bordersize 2, tag:pseudo
windowrulev2 = rounding 6, tag:pseudo

# Intellij
windowrule = noinitialfocus,class:jetbrains-idea.*,title:\^win(.\*)
windowrule = nofocus,class:jetbrains-idea.*,title:\^win(.\*)
windowrule = nofollowmouse,class:jetbrains-idea.*,title:\^win(.\*)

# General
windowrule = opacity 0.85 0.85 0.95, class:kitty
windowrule = opacity 0.95 0.90 0.95, class:codium
windowrule = opacity 0.90 0.90 0.95, class:jetbrains-idea-ce
windowrule = opacity 0.85 0.80 0.95, class:.*telegram.*
windowrule = opacity 0.85 0.80 0.95, class:.*Ferdium.*
windowrule = opacity 0.85 0.80 0.95, class:.*slack.*
windowrule = opacity 0.10 0.80 0.95, class:.*[Rr]ofi.*

# Gaming
windowrule = novrr on, fullscreen:1

# Overskride
windowrule = float, class:^(io.github.kaii_lb.Overskride)$
windowrule = size 1000 700, class:^(io.github.kaii_lb.Overskride)$
windowrule = move 100%-w-11 72, class:^(io.github.kaii_lb.Overskride)$ 
windowrule = pin, class:^(io.github.kaii_lb.Overskride)$ 
windowrule = stayfocused, class:^(io.github.kaii_lb.Overskride)$ 

# Pavucontrol
windowrule = float, class:^(org.pulseaudio.pavucontrol)$
windowrule = size 1000 700, class:^(org.pulseaudio.pavucontrol)$
windowrule = move 100%-w-11 72, class:^(org.pulseaudio.pavucontrol)$ 
windowrule = pin, class:^(org.pulseaudio.pavucontrol)$ 
windowrule = stayfocused, class:^(org.pulseaudio.pavucontrol)$ 

# Picture-in-a-Picture (PIP) rules: Oddly, some need re-duplication.  This is because the window for
# PIP changes after on first launch, and will not inherant the rules...
windowrulev2=opacity 0.95 0.75,title:^(Picture-in-Picture)$ # for opacity: [focus num] [bg num]
# Interestingly, the opacity rule above doesn't need the reduplication?
windowrulev2=pin,title:^(Picture-in-Picture)$ 
windowrulev2=float, title:^(Picture-in-Picture)$
windowrulev2=size 25% 25%,title:^(Picture-in-Picture)$ 
windowrulev2=move 72% 7%,title:^(Picture-in-Picture)$ 

windowrulev2 = opacity 0.0 override 0.0 override,class:^(xwaylandvideobridge)$
windowrulev2 = noanim,class:^(xwaylandvideobridge)$
windowrulev2 = noinitialfocus,class:^(xwaylandvideobridge)$
windowrulev2 = maxsize 1 1,class:^(xwaylandvideobridge)$
windowrulev2 = noblur,class:^(xwaylandvideobridge)$
