gesture = 3, horizontal, workspace
gesture = 4, up, dispatcher, exec, pkill $menu || $menu $menuModeRun
gesture = 4, vertical, special, magic
gesture = 3, swipe, resize
gesture = 4, left, dispatcher, movetoworkspace, special:magic
gesture = 4, right, dispatcher, movetoworkspace, +0
