exec-once = hyprpaper
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar

source = ~/.config/hypr/monitors.conf


# See https://wiki.hyprland.org/Configuring/Monitors/

windowrulev2 = suppressevent maximize, class:.*
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

source = ~/.config/hypr/style.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/gestures.conf
source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/waybar.conf
source = ~/.config/hypr/windowrules.conf
source = ~/.config/hypr/workspaces.conf

