exec-once = hyprpaper
exec-once = hypridle
exec-once = systemctl --user start hyprpolkitagent
exec-once = waybar

source = ~/.config/hypr/monitors.conf


workspace = 1, monitor:DP-1
workspace = 2, monitor:DP-1
workspace = 3, monitor:DP-1
workspace = 4, monitor:DP-1
workspace = 5, monitor:DP-1

source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/style.conf
source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/waybar.conf
windowrulev2 = suppressevent maximize, class:.*

windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

source = ~/.config/hypr/input.conf
source = ~/.config/hypr/keybindings.conf
source = ~/.config/hypr/style.conf
source = ~/.config/hypr/colors.conf
source = ~/.config/hypr/waybar.conf
source = ~/.config/hypr/windowrules.conf
