# layerrule = blur, swaync-control-center
# layerrule = ignorezero, swaync-control-center
layerrule = dimaround, swaync-control-center
# layerrule = blurpopups, swaync-control-center
# layerrule = xray true, swaync-control-center
