
# external monitors
monitor=DP-1, preferred, auto-left, 1
monitor=DP-2, preferred, auto, 1
monitor=HDMI-A-1, 2560x1440@144, auto, 1

# built in monitor
monitor=eDP-1, 1920x1080, auto, 1.25

# monitor disposition
workspace = 20, monitor:DP-1
workspace = 40, monitor:DP-2
workspace = 60, monitor:HDMI-A-1
