
# external monitors
monitor=DP-1, preferred, auto-up, 1
monitor=DP-2, preferred, auto-up, 1
monitor=HDMI-A-1, preferred, auto-up, 1

monitor=desc:GIGA-BYTE TECHNOLOGY CO. LTD. G34WQC 20482B007567, 3440x1440@100, auto-right, 1
monitor=desc:Philips Consumer Electronics Company PHL24E1N5300 UK02340060703, 1920x1080, auto-right, 1

# built in monitor
monitor=eDP-1, 1920x1080, auto, 1.25

# monitor disposition
workspace = 1, monitor:eDP-1
workspace = 2, monitor:eDP-1
workspace = 3, monitor:eDP-1
workspace = 4, monitor:eDP-1
workspace = 5, monitor:eDP-1
workspace = 6, monitor:eDP-1
workspace = 7, monitor:eDP-1
workspace = 8, monitor:eDP-1
workspace = 9, monitor:eDP-1
workspace = 10, monitor:eDP-1
workspace = 11, monitor:eDP-1
workspace = 12, monitor:eDP-1
workspace = 13, monitor:eDP-1
workspace = 14, monitor:eDP-1
workspace = 15, monitor:eDP-1
workspace = 16, monitor:eDP-1
workspace = 17, monitor:eDP-1
workspace = 18, monitor:eDP-1
workspace = 19, monitor:eDP-1
workspace = 20, monitor:eDP-1
workspace = 40, monitor:DP-1
workspace = 60, monitor:HDMI-A-1
